FROM node:lts AS install

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  DEBIAN_FRONTEND="noninteractive" \
  TZ="Asia/Shanghai"
COPY . ./code
WORKDIR /code
RUN apt-get update && \
  apt-get install curl libsecret-1-dev -y --fix-missing && \
  yarn

FROM install AS deploy
ENV NODE_ENV=production
RUN yarn build
CMD ["node", "packages/platform-server/dist/index.js"]

