// Auto generated content by `yarn cli update-workspace`
// DO NOT MODIFY THIS FILE MANUALLY
export const packageList = [
  {
    name: '@examples/duplicate-libs',
    version: '0.0.1',
    private: true,
    location: 'examples/duplicate-libs',
  },
  {
    name: '@examples/simple',
    version: '0.0.1',
    private: true,
    location: 'examples/simple',
  },
  {
    name: '@examples/split-chunks',
    version: '0.0.1',
    private: true,
    location: 'examples/split-chunks',
  },
  {
    name: '@perfsee/bundle-analyzer',
    version: '0.0.1',
    private: false,
    location: 'packages/bundle-analyzer',
  },
  {
    name: '@perfsee/bundle-report',
    version: '0.0.1',
    private: true,
    location: 'packages/bundle-report',
  },
  {
    name: '@perfsee/chrome-finder',
    version: '0.0.1',
    private: true,
    location: 'packages/chrome-finder',
  },
  {
    name: '@perfsee/components',
    version: '0.0.1',
    private: true,
    location: 'packages/components',
  },
  {
    name: '@perfsee/dls',
    version: '0.0.1',
    private: true,
    location: 'packages/dls',
  },
  {
    name: '@perfsee/email-templates',
    version: '0.0.1',
    private: true,
    location: 'packages/email-templates',
  },
  {
    name: '@perfsee/flamechart',
    version: '0.0.1',
    private: true,
    location: 'packages/flamechart',
  },
  {
    name: '@perfsee/ori',
    version: '0.0.1',
    private: true,
    location: 'packages/ori',
  },
  {
    name: '@perfsee/platform-server',
    version: '0.0.1',
    private: true,
    location: 'packages/platform-server',
  },
  {
    name: '@perfsee/platform',
    version: '0.0.1',
    private: true,
    location: 'packages/platform',
  },
  {
    name: '@perfsee/schema',
    version: '0.0.1',
    private: true,
    location: 'packages/schema',
  },
  {
    name: '@perfsee/server-common',
    version: '0.0.1',
    private: true,
    location: 'packages/server-common',
  },
  {
    name: '@perfsee/shared',
    version: '0.0.1',
    private: true,
    location: 'packages/shared',
  },
  {
    name: '@perfsee/source-coverage',
    version: '0.0.1',
    private: true,
    location: 'packages/source-coverage',
  },
  {
    name: '@perfsee/tracehouse',
    version: '0.0.1',
    private: true,
    location: 'packages/tracehouse',
  },
  {
    name: '@perfsee/treemap',
    version: '0.0.1',
    private: true,
    location: 'packages/treemap',
  },
  {
    name: '@perfsee/utils',
    version: '0.0.1',
    private: false,
    location: 'packages/utils',
  },
  {
    name: 'perfsee-vscode',
    version: '0.0.1',
    private: true,
    location: 'packages/vscode-extension',
  },
  {
    name: '@perfsee/esbuild',
    version: '0.0.1',
    private: false,
    location: 'packages/plugins/esbuild',
  },
  {
    name: '@perfsee/rollup',
    version: '0.0.1',
    private: false,
    location: 'packages/plugins/rollup',
  },
  {
    name: '@perfsee/plugin-utils',
    version: '0.0.1',
    private: false,
    location: 'packages/plugins/utils',
  },
  {
    name: '@perfsee/webpack',
    version: '0.0.1',
    private: false,
    location: 'packages/plugins/webpack',
  },
  {
    name: '@perfsee/job-runner-bundle',
    version: '0.0.1',
    private: true,
    location: 'packages/runner/bundle',
  },
  {
    name: '@perfsee/job-runner',
    version: '0.0.1',
    private: true,
    location: 'packages/runner/executor',
  },
  {
    name: '@perfsee/job-runner-lab',
    version: '0.0.1',
    private: true,
    location: 'packages/runner/lab',
  },
  {
    name: '@perfsee/job-runner-shared',
    version: '0.0.1',
    private: true,
    location: 'packages/runner/shared',
  },
  {
    name: '@perfsee/job-runner-source',
    version: '0.0.1',
    private: true,
    location: 'packages/runner/source',
  },
] as const

export type PackageName = typeof packageList[number]['name']
