[package]
edition = "2018"
name = "ori"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1"
napi = {version = "1", features = ["serde-json"]}
napi-derive = "2"
rayon = "1.5.0"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sourcemap = "6"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
insta = "1.6.2"
expect-test = "1.0"

[[bench]]
harness = false
name = "chrome_profile"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"
