[package]
edition = "2018"
name = "ori"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1"
napi = {version = "2", features = ["serde-json"]}
napi-derive = {version = "2", default-features = false, features = ["type-def"]}
rayon = "1.5.0"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sourcemap = "6"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.6"
expect-test = "1.4"
insta = {version = "1.19.0", features = ["json"]}

[[bench]]
harness = false
name = "chrome_profile"

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc-rust = {version = "0.2"}

[target.'cfg(all(target_os = "linux", not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
mimalloc-rust = {version = "0.2", features = ["local-dynamic-tls"]}

[build-dependencies]
napi-build = "2"
