/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function analyseProfile(
  profilePath: string,
  bundleMetaPath: string,
  reactLocationsPath?: string | undefined | null,
  callFramesPath?: string | undefined | null,
  debugMode?: boolean | undefined | null,
): Promise<string>
export function generateDocs(): Record<string, string>
