name: Release packages

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  release-npm-packages:
    if: "${{ contains(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: |
          yarn codegen
          yarn build:npm
      - name: Publish
        run: yarn release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-vscode:
    if: "${{ contains(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSC_MARKET_PAT }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: |
          yarn codegen
          yarn cli vscode build
          yarn cli vscode build:webview
      - name: Publish Vscode Extension (pre-release)
        if: ${{ contains(github.ref_name, 'alpha') }}
        run: |
          npm install -g vsce
          cd packages/vscode-extension
          vsce publish --pre-release --no-dependencies --no-git-tag-version --no-update-package-json --baseImagesUrl https://github.com/perfsee/perfsee/raw/main/packages/vscode-extension `date +'%Y.%-m.%-d%H%M'`
      - name: Publish Vscode Extension
        if: ${{ contains(github.ref_name, 'alpha') == false }}
        run: |
          npm install -g vsce
          cd packages/vscode-extension
          vsce publish --no-dependencies --no-git-tag-version --no-update-package-json --baseImagesUrl https://github.com/perfsee/perfsee/raw/main/packages/vscode-extension
  release-scripts:
    if: "${{ contains(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn install
      - name: Build and Upload scripts in docker
        uses: addnab/docker-run-action@v3
        env:
          PERFSEE_REGISTRATION_TOKEN: ${{ secrets.PERFSEE_REGISTRATION_TOKEN }}
        with:
          image: ghcr.io/perfsee/perfsee/develop:latest
          options: -v ${{ github.workspace }}:/build -w /build -e PERFSEE_REGISTRATION_TOKEN
          run: |
            yarn tsc -b ./tsconfigs/tsconfig.runner.json --verbose
            yarn build:rs
            yarn cli upload-scripts
